<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/Incentives/protos/chromeIncentives.proto

namespace GPBMetadata\Src\Incentives\Protos;

class ChromeIncentives
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A6\x0A,src/Incentives/protos/chromeIncentives.protob\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

