<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/Incentives/protos/lenderDeskIncentives.proto

namespace GPBMetadata\Src\Incentives\Protos;

class LenderDeskIncentives
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0Ab\x0A0src/Incentives/protos/lenderDeskIncentives.proto\"&\x0A\x13LenderDeskIncentive\x1A\x0F\x0A\x0DIncentiveBodyb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

