<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/Incentives/protos/genericIncentive.proto

/**
 * Protobuf type <code>CashValueType</code>
 */
class CashValueType
{
    /**
     * Generated from protobuf enum <code>CASH_VALUE_UNDETERMINED = 0;</code>
     */
    const CASH_VALUE_UNDETERMINED = 0;
    /**
     * Generated from protobuf enum <code>CASH_VALUE_STANDARD = 1;</code>
     */
    const CASH_VALUE_STANDARD = 1;
    /**
     * Generated from protobuf enum <code>CASH_VALUE_TERM_BASED = 2;</code>
     */
    const CASH_VALUE_TERM_BASED = 2;
    /**
     * Generated from protobuf enum <code>CASH_VALUE_PERCENTAGE_BASED = 3;</code>
     */
    const CASH_VALUE_PERCENTAGE_BASED = 3;

    private static $valueToName = [
        self::CASH_VALUE_UNDETERMINED => 'CASH_VALUE_UNDETERMINED',
        self::CASH_VALUE_STANDARD => 'CASH_VALUE_STANDARD',
        self::CASH_VALUE_TERM_BASED => 'CASH_VALUE_TERM_BASED',
        self::CASH_VALUE_PERCENTAGE_BASED => 'CASH_VALUE_PERCENTAGE_BASED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

