<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/Incentives/protos/genericIncentive.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Chrome</code>
 */
class Chrome extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string style_id = 1;</code>
     */
    protected $style_id = '';
    /**
     * Generated from protobuf field <code>string model = 2;</code>
     */
    protected $model = '';
    /**
     * Generated from protobuf field <code>string trim = 3;</code>
     */
    protected $trim = '';
    /**
     * Generated from protobuf field <code>string stock_image = 4;</code>
     */
    protected $stock_image = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $style_id
     *     @type string $model
     *     @type string $trim
     *     @type string $stock_image
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Src\Incentives\Protos\GenericIncentive::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string style_id = 1;</code>
     * @return string
     */
    public function getStyleId()
    {
        return $this->style_id;
    }

    /**
     * Generated from protobuf field <code>string style_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStyleId($var)
    {
        GPBUtil::checkString($var, True);
        $this->style_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string model = 2;</code>
     * @return string
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * Generated from protobuf field <code>string model = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setModel($var)
    {
        GPBUtil::checkString($var, True);
        $this->model = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string trim = 3;</code>
     * @return string
     */
    public function getTrim()
    {
        return $this->trim;
    }

    /**
     * Generated from protobuf field <code>string trim = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTrim($var)
    {
        GPBUtil::checkString($var, True);
        $this->trim = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string stock_image = 4;</code>
     * @return string
     */
    public function getStockImage()
    {
        return $this->stock_image;
    }

    /**
     * Generated from protobuf field <code>string stock_image = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStockImage($var)
    {
        GPBUtil::checkString($var, True);
        $this->stock_image = $var;

        return $this;
    }

}

