<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/Incentives/protos/genericIncentive.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Incentive</code>
 */
class Incentive extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .Incentive.IncentiveBody> incentives = 1;</code>
     */
    private $incentives;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $incentives
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Src\Incentives\Protos\GenericIncentive::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .Incentive.IncentiveBody> incentives = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getIncentives()
    {
        return $this->incentives;
    }

    /**
     * Generated from protobuf field <code>map<string, .Incentive.IncentiveBody> incentives = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setIncentives($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Incentive\IncentiveBody::class);
        $this->incentives = $arr;

        return $this;
    }

}

