<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/Incentives/protos/genericIncentive.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Vehicle</code>
 */
class Vehicle extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string vin = 1;</code>
     */
    protected $vin = '';
    /**
     * Generated from protobuf field <code>int32 year = 2;</code>
     */
    protected $year = 0;
    /**
     * Generated from protobuf field <code>string make = 3;</code>
     */
    protected $make = '';
    /**
     * Generated from protobuf field <code>string model = 4;</code>
     */
    protected $model = '';
    /**
     * Generated from protobuf field <code>string trim = 5;</code>
     */
    protected $trim = '';
    /**
     * Generated from protobuf field <code>string body = 6;</code>
     */
    protected $body = '';
    /**
     * Generated from protobuf field <code>int32 msrp = 7;</code>
     */
    protected $msrp = 0;
    /**
     * Generated from protobuf field <code>string transmission_description = 8;</code>
     */
    protected $transmission_description = '';
    /**
     * Generated from protobuf field <code>string model_number = 9;</code>
     */
    protected $model_number = '';
    /**
     * Generated from protobuf field <code>repeated .PackageCode packagecode = 10;</code>
     */
    private $packagecode;
    /**
     * Generated from protobuf field <code>string thumbnail = 11;</code>
     */
    protected $thumbnail = '';
    /**
     * Generated from protobuf field <code>string title = 12;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>.Chrome chrome = 13;</code>
     */
    protected $chrome = null;
    /**
     * Generated from protobuf field <code>string chrome_style_id = 14;</code>
     */
    protected $chrome_style_id = '';
    /**
     * Generated from protobuf field <code>string OEMStockImage = 15;</code>
     */
    protected $OEMStockImage = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $vin
     *     @type int $year
     *     @type string $make
     *     @type string $model
     *     @type string $trim
     *     @type string $body
     *     @type int $msrp
     *     @type string $transmission_description
     *     @type string $model_number
     *     @type array<\PackageCode>|\Google\Protobuf\Internal\RepeatedField $packagecode
     *     @type string $thumbnail
     *     @type string $title
     *     @type \Chrome $chrome
     *     @type string $chrome_style_id
     *     @type string $OEMStockImage
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Src\Incentives\Protos\GenericIncentive::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string vin = 1;</code>
     * @return string
     */
    public function getVin()
    {
        return $this->vin;
    }

    /**
     * Generated from protobuf field <code>string vin = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVin($var)
    {
        GPBUtil::checkString($var, True);
        $this->vin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 year = 2;</code>
     * @return int
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * Generated from protobuf field <code>int32 year = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setYear($var)
    {
        GPBUtil::checkInt32($var);
        $this->year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string make = 3;</code>
     * @return string
     */
    public function getMake()
    {
        return $this->make;
    }

    /**
     * Generated from protobuf field <code>string make = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMake($var)
    {
        GPBUtil::checkString($var, True);
        $this->make = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string model = 4;</code>
     * @return string
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * Generated from protobuf field <code>string model = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setModel($var)
    {
        GPBUtil::checkString($var, True);
        $this->model = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string trim = 5;</code>
     * @return string
     */
    public function getTrim()
    {
        return $this->trim;
    }

    /**
     * Generated from protobuf field <code>string trim = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTrim($var)
    {
        GPBUtil::checkString($var, True);
        $this->trim = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string body = 6;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>string body = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 msrp = 7;</code>
     * @return int
     */
    public function getMsrp()
    {
        return $this->msrp;
    }

    /**
     * Generated from protobuf field <code>int32 msrp = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setMsrp($var)
    {
        GPBUtil::checkInt32($var);
        $this->msrp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string transmission_description = 8;</code>
     * @return string
     */
    public function getTransmissionDescription()
    {
        return $this->transmission_description;
    }

    /**
     * Generated from protobuf field <code>string transmission_description = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setTransmissionDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->transmission_description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string model_number = 9;</code>
     * @return string
     */
    public function getModelNumber()
    {
        return $this->model_number;
    }

    /**
     * Generated from protobuf field <code>string model_number = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setModelNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->model_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .PackageCode packagecode = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPackagecode()
    {
        return $this->packagecode;
    }

    /**
     * Generated from protobuf field <code>repeated .PackageCode packagecode = 10;</code>
     * @param array<\PackageCode>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPackagecode($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \PackageCode::class);
        $this->packagecode = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string thumbnail = 11;</code>
     * @return string
     */
    public function getThumbnail()
    {
        return $this->thumbnail;
    }

    /**
     * Generated from protobuf field <code>string thumbnail = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setThumbnail($var)
    {
        GPBUtil::checkString($var, True);
        $this->thumbnail = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 12;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Chrome chrome = 13;</code>
     * @return \Chrome|null
     */
    public function getChrome()
    {
        return $this->chrome;
    }

    public function hasChrome()
    {
        return isset($this->chrome);
    }

    public function clearChrome()
    {
        unset($this->chrome);
    }

    /**
     * Generated from protobuf field <code>.Chrome chrome = 13;</code>
     * @param \Chrome $var
     * @return $this
     */
    public function setChrome($var)
    {
        GPBUtil::checkMessage($var, \Chrome::class);
        $this->chrome = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string chrome_style_id = 14;</code>
     * @return string
     */
    public function getChromeStyleId()
    {
        return $this->chrome_style_id;
    }

    /**
     * Generated from protobuf field <code>string chrome_style_id = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setChromeStyleId($var)
    {
        GPBUtil::checkString($var, True);
        $this->chrome_style_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string OEMStockImage = 15;</code>
     * @return string
     */
    public function getOEMStockImage()
    {
        return $this->OEMStockImage;
    }

    /**
     * Generated from protobuf field <code>string OEMStockImage = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setOEMStockImage($var)
    {
        GPBUtil::checkString($var, True);
        $this->OEMStockImage = $var;

        return $this;
    }

}

