<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/Incentives/protos/genericIncentive.proto

namespace Incentive;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Incentive.CashIncentives</code>
 */
class CashIncentives extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool is_stackable = 1;</code>
     */
    protected $is_stackable = false;
    /**
     * Generated from protobuf field <code>string group_affiliation = 2;</code>
     */
    protected $group_affiliation = '';
    /**
     * Generated from protobuf field <code>string previous_ownership = 3;</code>
     */
    protected $previous_ownership = '';
    /**
     * Generated from protobuf field <code>repeated string delivery_type_list = 4;</code>
     */
    private $delivery_type_list;
    /**
     * Generated from protobuf field <code>int32 program_id = 5;</code>
     */
    protected $program_id = 0;
    /**
     * Generated from protobuf field <code>string program_number = 6;</code>
     */
    protected $program_number = '';
    /**
     * Generated from protobuf field <code>string name = 7;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>int32 total_cash = 8;</code>
     */
    protected $total_cash = 0;
    /**
     * Generated from protobuf field <code>.CashValueType cash_value_type = 9;</code>
     */
    protected $cash_value_type = 0;
    /**
     * Generated from protobuf field <code>int32 cash_value_terms = 10;</code>
     */
    protected $cash_value_terms = 0;
    /**
     * Generated from protobuf field <code>string start_date = 11;</code>
     */
    protected $start_date = '';
    /**
     * Generated from protobuf field <code>string end_date = 12;</code>
     */
    protected $end_date = '';
    /**
     * Generated from protobuf field <code>.Incentive.Detail details = 13;</code>
     */
    protected $details = null;
    /**
     * Generated from protobuf field <code>int32 total = 14;</code>
     */
    protected $total = 0;
    /**
     * Generated from protobuf field <code>string hash = 15;</code>
     */
    protected $hash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $is_stackable
     *     @type string $group_affiliation
     *     @type string $previous_ownership
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $delivery_type_list
     *     @type int $program_id
     *     @type string $program_number
     *     @type string $name
     *     @type int $total_cash
     *     @type int $cash_value_type
     *     @type int $cash_value_terms
     *     @type string $start_date
     *     @type string $end_date
     *     @type \Incentive\Detail $details
     *     @type int $total
     *     @type string $hash
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Src\Incentives\Protos\GenericIncentive::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool is_stackable = 1;</code>
     * @return bool
     */
    public function getIsStackable()
    {
        return $this->is_stackable;
    }

    /**
     * Generated from protobuf field <code>bool is_stackable = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsStackable($var)
    {
        GPBUtil::checkBool($var);
        $this->is_stackable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string group_affiliation = 2;</code>
     * @return string
     */
    public function getGroupAffiliation()
    {
        return $this->group_affiliation;
    }

    /**
     * Generated from protobuf field <code>string group_affiliation = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupAffiliation($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_affiliation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string previous_ownership = 3;</code>
     * @return string
     */
    public function getPreviousOwnership()
    {
        return $this->previous_ownership;
    }

    /**
     * Generated from protobuf field <code>string previous_ownership = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPreviousOwnership($var)
    {
        GPBUtil::checkString($var, True);
        $this->previous_ownership = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string delivery_type_list = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDeliveryTypeList()
    {
        return $this->delivery_type_list;
    }

    /**
     * Generated from protobuf field <code>repeated string delivery_type_list = 4;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDeliveryTypeList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->delivery_type_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 program_id = 5;</code>
     * @return int
     */
    public function getProgramId()
    {
        return $this->program_id;
    }

    /**
     * Generated from protobuf field <code>int32 program_id = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setProgramId($var)
    {
        GPBUtil::checkInt32($var);
        $this->program_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string program_number = 6;</code>
     * @return string
     */
    public function getProgramNumber()
    {
        return $this->program_number;
    }

    /**
     * Generated from protobuf field <code>string program_number = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setProgramNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->program_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 7;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 total_cash = 8;</code>
     * @return int
     */
    public function getTotalCash()
    {
        return $this->total_cash;
    }

    /**
     * Generated from protobuf field <code>int32 total_cash = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalCash($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_cash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.CashValueType cash_value_type = 9;</code>
     * @return int
     */
    public function getCashValueType()
    {
        return $this->cash_value_type;
    }

    /**
     * Generated from protobuf field <code>.CashValueType cash_value_type = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setCashValueType($var)
    {
        GPBUtil::checkEnum($var, \CashValueType::class);
        $this->cash_value_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cash_value_terms = 10;</code>
     * @return int
     */
    public function getCashValueTerms()
    {
        return $this->cash_value_terms;
    }

    /**
     * Generated from protobuf field <code>int32 cash_value_terms = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setCashValueTerms($var)
    {
        GPBUtil::checkInt32($var);
        $this->cash_value_terms = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string start_date = 11;</code>
     * @return string
     */
    public function getStartDate()
    {
        return $this->start_date;
    }

    /**
     * Generated from protobuf field <code>string start_date = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setStartDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string end_date = 12;</code>
     * @return string
     */
    public function getEndDate()
    {
        return $this->end_date;
    }

    /**
     * Generated from protobuf field <code>string end_date = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setEndDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->end_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Incentive.Detail details = 13;</code>
     * @return \Incentive\Detail|null
     */
    public function getDetails()
    {
        return $this->details;
    }

    public function hasDetails()
    {
        return isset($this->details);
    }

    public function clearDetails()
    {
        unset($this->details);
    }

    /**
     * Generated from protobuf field <code>.Incentive.Detail details = 13;</code>
     * @param \Incentive\Detail $var
     * @return $this
     */
    public function setDetails($var)
    {
        GPBUtil::checkMessage($var, \Incentive\Detail::class);
        $this->details = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 total = 14;</code>
     * @return int
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>int32 total = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt32($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string hash = 15;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Generated from protobuf field <code>string hash = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->hash = $var;

        return $this;
    }

}

