<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/Incentives/protos/genericIncentive.proto

namespace Incentive;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Incentive.Dealer</code>
 */
class Dealer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string Id = 2;</code>
     */
    protected $Id = '';
    /**
     * Generated from protobuf field <code>optional string CCID = 3;</code>
     */
    protected $CCID = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $Id
     *     @type string $CCID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Src\Incentives\Protos\GenericIncentive::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Id = 2;</code>
     * @return string
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * Generated from protobuf field <code>string Id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->Id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string CCID = 3;</code>
     * @return string
     */
    public function getCCID()
    {
        return isset($this->CCID) ? $this->CCID : '';
    }

    public function hasCCID()
    {
        return isset($this->CCID);
    }

    public function clearCCID()
    {
        unset($this->CCID);
    }

    /**
     * Generated from protobuf field <code>optional string CCID = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCCID($var)
    {
        GPBUtil::checkString($var, True);
        $this->CCID = $var;

        return $this;
    }

}

