<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/Incentives/protos/genericIncentive.proto

namespace Incentive;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Incentive.IncentiveBody</code>
 */
class IncentiveBody extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string title = 1;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>repeated .Incentive.CashIncentives cash = 2;</code>
     */
    private $cash;
    /**
     * Generated from protobuf field <code>repeated .Incentive.CashIncentives cash_all = 3;</code>
     */
    private $cash_all;
    /**
     * Generated from protobuf field <code>.Incentive.FinanceIncentives finance = 4;</code>
     */
    protected $finance = null;
    /**
     * Generated from protobuf field <code>repeated .Incentive.FinanceIncentives finance_all = 5;</code>
     */
    private $finance_all;
    /**
     * Generated from protobuf field <code>.Incentive.LeaseIncentives lease = 6;</code>
     */
    protected $lease = null;
    /**
     * Generated from protobuf field <code>repeated .Incentive.LeaseIncentives lease_all = 7;</code>
     */
    private $lease_all;
    /**
     * Generated from protobuf field <code>map<string, .Incentive.SpecialIncentives> specials = 8;</code>
     */
    private $specials;
    /**
     * Generated from protobuf field <code>repeated .Incentive.Disclaimers disclaimers = 9;</code>
     */
    private $disclaimers;
    /**
     * Generated from protobuf field <code>.Vehicle vehicle = 10;</code>
     */
    protected $vehicle = null;
    /**
     * Generated from protobuf field <code>string timestamp = 11;</code>
     */
    protected $timestamp = '';
    /**
     * Generated from protobuf field <code>string IP = 12;</code>
     */
    protected $IP = '';
    /**
     * Generated from protobuf field <code>string zipcode = 13;</code>
     */
    protected $zipcode = '';
    /**
     * Generated from protobuf field <code>.Incentive.Dealer dealer = 14;</code>
     */
    protected $dealer = null;
    /**
     * Generated from protobuf field <code>.Incentive.Request request = 15;</code>
     */
    protected $request = null;
    /**
     * Generated from protobuf field <code>repeated string vin = 16;</code>
     */
    private $vin;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $title
     *     @type array<\Incentive\CashIncentives>|\Google\Protobuf\Internal\RepeatedField $cash
     *     @type array<\Incentive\CashIncentives>|\Google\Protobuf\Internal\RepeatedField $cash_all
     *     @type \Incentive\FinanceIncentives $finance
     *     @type array<\Incentive\FinanceIncentives>|\Google\Protobuf\Internal\RepeatedField $finance_all
     *     @type \Incentive\LeaseIncentives $lease
     *     @type array<\Incentive\LeaseIncentives>|\Google\Protobuf\Internal\RepeatedField $lease_all
     *     @type array|\Google\Protobuf\Internal\MapField $specials
     *     @type array<\Incentive\Disclaimers>|\Google\Protobuf\Internal\RepeatedField $disclaimers
     *     @type \Vehicle $vehicle
     *     @type string $timestamp
     *     @type string $IP
     *     @type string $zipcode
     *     @type \Incentive\Dealer $dealer
     *     @type \Incentive\Request $request
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $vin
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Src\Incentives\Protos\GenericIncentive::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Incentive.CashIncentives cash = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCash()
    {
        return $this->cash;
    }

    /**
     * Generated from protobuf field <code>repeated .Incentive.CashIncentives cash = 2;</code>
     * @param array<\Incentive\CashIncentives>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCash($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Incentive\CashIncentives::class);
        $this->cash = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Incentive.CashIncentives cash_all = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCashAll()
    {
        return $this->cash_all;
    }

    /**
     * Generated from protobuf field <code>repeated .Incentive.CashIncentives cash_all = 3;</code>
     * @param array<\Incentive\CashIncentives>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCashAll($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Incentive\CashIncentives::class);
        $this->cash_all = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Incentive.FinanceIncentives finance = 4;</code>
     * @return \Incentive\FinanceIncentives|null
     */
    public function getFinance()
    {
        return $this->finance;
    }

    public function hasFinance()
    {
        return isset($this->finance);
    }

    public function clearFinance()
    {
        unset($this->finance);
    }

    /**
     * Generated from protobuf field <code>.Incentive.FinanceIncentives finance = 4;</code>
     * @param \Incentive\FinanceIncentives $var
     * @return $this
     */
    public function setFinance($var)
    {
        GPBUtil::checkMessage($var, \Incentive\FinanceIncentives::class);
        $this->finance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Incentive.FinanceIncentives finance_all = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFinanceAll()
    {
        return $this->finance_all;
    }

    /**
     * Generated from protobuf field <code>repeated .Incentive.FinanceIncentives finance_all = 5;</code>
     * @param array<\Incentive\FinanceIncentives>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFinanceAll($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Incentive\FinanceIncentives::class);
        $this->finance_all = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Incentive.LeaseIncentives lease = 6;</code>
     * @return \Incentive\LeaseIncentives|null
     */
    public function getLease()
    {
        return $this->lease;
    }

    public function hasLease()
    {
        return isset($this->lease);
    }

    public function clearLease()
    {
        unset($this->lease);
    }

    /**
     * Generated from protobuf field <code>.Incentive.LeaseIncentives lease = 6;</code>
     * @param \Incentive\LeaseIncentives $var
     * @return $this
     */
    public function setLease($var)
    {
        GPBUtil::checkMessage($var, \Incentive\LeaseIncentives::class);
        $this->lease = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Incentive.LeaseIncentives lease_all = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLeaseAll()
    {
        return $this->lease_all;
    }

    /**
     * Generated from protobuf field <code>repeated .Incentive.LeaseIncentives lease_all = 7;</code>
     * @param array<\Incentive\LeaseIncentives>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLeaseAll($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Incentive\LeaseIncentives::class);
        $this->lease_all = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .Incentive.SpecialIncentives> specials = 8;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getSpecials()
    {
        return $this->specials;
    }

    /**
     * Generated from protobuf field <code>map<string, .Incentive.SpecialIncentives> specials = 8;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setSpecials($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Incentive\SpecialIncentives::class);
        $this->specials = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Incentive.Disclaimers disclaimers = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDisclaimers()
    {
        return $this->disclaimers;
    }

    /**
     * Generated from protobuf field <code>repeated .Incentive.Disclaimers disclaimers = 9;</code>
     * @param array<\Incentive\Disclaimers>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDisclaimers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Incentive\Disclaimers::class);
        $this->disclaimers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Vehicle vehicle = 10;</code>
     * @return \Vehicle|null
     */
    public function getVehicle()
    {
        return $this->vehicle;
    }

    public function hasVehicle()
    {
        return isset($this->vehicle);
    }

    public function clearVehicle()
    {
        unset($this->vehicle);
    }

    /**
     * Generated from protobuf field <code>.Vehicle vehicle = 10;</code>
     * @param \Vehicle $var
     * @return $this
     */
    public function setVehicle($var)
    {
        GPBUtil::checkMessage($var, \Vehicle::class);
        $this->vehicle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string timestamp = 11;</code>
     * @return string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>string timestamp = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string IP = 12;</code>
     * @return string
     */
    public function getIP()
    {
        return $this->IP;
    }

    /**
     * Generated from protobuf field <code>string IP = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setIP($var)
    {
        GPBUtil::checkString($var, True);
        $this->IP = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string zipcode = 13;</code>
     * @return string
     */
    public function getZipcode()
    {
        return $this->zipcode;
    }

    /**
     * Generated from protobuf field <code>string zipcode = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setZipcode($var)
    {
        GPBUtil::checkString($var, True);
        $this->zipcode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Incentive.Dealer dealer = 14;</code>
     * @return \Incentive\Dealer|null
     */
    public function getDealer()
    {
        return $this->dealer;
    }

    public function hasDealer()
    {
        return isset($this->dealer);
    }

    public function clearDealer()
    {
        unset($this->dealer);
    }

    /**
     * Generated from protobuf field <code>.Incentive.Dealer dealer = 14;</code>
     * @param \Incentive\Dealer $var
     * @return $this
     */
    public function setDealer($var)
    {
        GPBUtil::checkMessage($var, \Incentive\Dealer::class);
        $this->dealer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Incentive.Request request = 15;</code>
     * @return \Incentive\Request|null
     */
    public function getRequest()
    {
        return $this->request;
    }

    public function hasRequest()
    {
        return isset($this->request);
    }

    public function clearRequest()
    {
        unset($this->request);
    }

    /**
     * Generated from protobuf field <code>.Incentive.Request request = 15;</code>
     * @param \Incentive\Request $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkMessage($var, \Incentive\Request::class);
        $this->request = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string vin = 16;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVin()
    {
        return $this->vin;
    }

    /**
     * Generated from protobuf field <code>repeated string vin = 16;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVin($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->vin = $arr;

        return $this;
    }

}

