<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/Incentives/protos/genericIncentive.proto

namespace Incentive;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Incentive.LeaseIncentives</code>
 */
class LeaseIncentives extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string source = 1;</code>
     */
    protected $source = '';
    /**
     * Generated from protobuf field <code>string group_affiliation = 2;</code>
     */
    protected $group_affiliation = '';
    /**
     * Generated from protobuf field <code>string previous_ownership = 3;</code>
     */
    protected $previous_ownership = '';
    /**
     * Generated from protobuf field <code>repeated string delivery_type_list = 4;</code>
     */
    private $delivery_type_list;
    /**
     * Generated from protobuf field <code>string FinancialInstitution = 5;</code>
     */
    protected $FinancialInstitution = '';
    /**
     * Generated from protobuf field <code>int32 program_id = 6;</code>
     */
    protected $program_id = 0;
    /**
     * Generated from protobuf field <code>string program_number = 7;</code>
     */
    protected $program_number = '';
    /**
     * Generated from protobuf field <code>string name = 8;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>repeated .Incentive.CashIncentives cash_incentive = 9;</code>
     */
    private $cash_incentive;
    /**
     * Generated from protobuf field <code>string start_date = 10;</code>
     */
    protected $start_date = '';
    /**
     * Generated from protobuf field <code>string end_date = 11;</code>
     */
    protected $end_date = '';
    /**
     * Generated from protobuf field <code>.Incentive.Detail details = 12;</code>
     */
    protected $details = null;
    /**
     * Generated from protobuf field <code>.Incentive.Terms terms = 13;</code>
     */
    protected $terms = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $source
     *     @type string $group_affiliation
     *     @type string $previous_ownership
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $delivery_type_list
     *     @type string $FinancialInstitution
     *     @type int $program_id
     *     @type string $program_number
     *     @type string $name
     *     @type array<\Incentive\CashIncentives>|\Google\Protobuf\Internal\RepeatedField $cash_incentive
     *     @type string $start_date
     *     @type string $end_date
     *     @type \Incentive\Detail $details
     *     @type \Incentive\Terms $terms
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Src\Incentives\Protos\GenericIncentive::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string source = 1;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * Generated from protobuf field <code>string source = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string group_affiliation = 2;</code>
     * @return string
     */
    public function getGroupAffiliation()
    {
        return $this->group_affiliation;
    }

    /**
     * Generated from protobuf field <code>string group_affiliation = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupAffiliation($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_affiliation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string previous_ownership = 3;</code>
     * @return string
     */
    public function getPreviousOwnership()
    {
        return $this->previous_ownership;
    }

    /**
     * Generated from protobuf field <code>string previous_ownership = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPreviousOwnership($var)
    {
        GPBUtil::checkString($var, True);
        $this->previous_ownership = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string delivery_type_list = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDeliveryTypeList()
    {
        return $this->delivery_type_list;
    }

    /**
     * Generated from protobuf field <code>repeated string delivery_type_list = 4;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDeliveryTypeList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->delivery_type_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string FinancialInstitution = 5;</code>
     * @return string
     */
    public function getFinancialInstitution()
    {
        return $this->FinancialInstitution;
    }

    /**
     * Generated from protobuf field <code>string FinancialInstitution = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFinancialInstitution($var)
    {
        GPBUtil::checkString($var, True);
        $this->FinancialInstitution = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 program_id = 6;</code>
     * @return int
     */
    public function getProgramId()
    {
        return $this->program_id;
    }

    /**
     * Generated from protobuf field <code>int32 program_id = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setProgramId($var)
    {
        GPBUtil::checkInt32($var);
        $this->program_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string program_number = 7;</code>
     * @return string
     */
    public function getProgramNumber()
    {
        return $this->program_number;
    }

    /**
     * Generated from protobuf field <code>string program_number = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setProgramNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->program_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 8;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Incentive.CashIncentives cash_incentive = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCashIncentive()
    {
        return $this->cash_incentive;
    }

    /**
     * Generated from protobuf field <code>repeated .Incentive.CashIncentives cash_incentive = 9;</code>
     * @param array<\Incentive\CashIncentives>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCashIncentive($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Incentive\CashIncentives::class);
        $this->cash_incentive = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string start_date = 10;</code>
     * @return string
     */
    public function getStartDate()
    {
        return $this->start_date;
    }

    /**
     * Generated from protobuf field <code>string start_date = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setStartDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string end_date = 11;</code>
     * @return string
     */
    public function getEndDate()
    {
        return $this->end_date;
    }

    /**
     * Generated from protobuf field <code>string end_date = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setEndDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->end_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Incentive.Detail details = 12;</code>
     * @return \Incentive\Detail|null
     */
    public function getDetails()
    {
        return $this->details;
    }

    public function hasDetails()
    {
        return isset($this->details);
    }

    public function clearDetails()
    {
        unset($this->details);
    }

    /**
     * Generated from protobuf field <code>.Incentive.Detail details = 12;</code>
     * @param \Incentive\Detail $var
     * @return $this
     */
    public function setDetails($var)
    {
        GPBUtil::checkMessage($var, \Incentive\Detail::class);
        $this->details = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Incentive.Terms terms = 13;</code>
     * @return \Incentive\Terms|null
     */
    public function getTerms()
    {
        return $this->terms;
    }

    public function hasTerms()
    {
        return isset($this->terms);
    }

    public function clearTerms()
    {
        unset($this->terms);
    }

    /**
     * Generated from protobuf field <code>.Incentive.Terms terms = 13;</code>
     * @param \Incentive\Terms $var
     * @return $this
     */
    public function setTerms($var)
    {
        GPBUtil::checkMessage($var, \Incentive\Terms::class);
        $this->terms = $var;

        return $this;
    }

}

