<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/Incentives/protos/genericIncentive.proto

namespace Incentive;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Incentive.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ref = 1;</code>
     */
    protected $ref = '';
    /**
     * Generated from protobuf field <code>string dealer_id = 2;</code>
     */
    protected $dealer_id = '';
    /**
     * Generated from protobuf field <code>string zipcode = 3;</code>
     */
    protected $zipcode = '';
    /**
     * Generated from protobuf field <code>optional string is_inventory_sync = 4;</code>
     */
    protected $is_inventory_sync = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ref
     *     @type string $dealer_id
     *     @type string $zipcode
     *     @type string $is_inventory_sync
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Src\Incentives\Protos\GenericIncentive::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ref = 1;</code>
     * @return string
     */
    public function getRef()
    {
        return $this->ref;
    }

    /**
     * Generated from protobuf field <code>string ref = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRef($var)
    {
        GPBUtil::checkString($var, True);
        $this->ref = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dealer_id = 2;</code>
     * @return string
     */
    public function getDealerId()
    {
        return $this->dealer_id;
    }

    /**
     * Generated from protobuf field <code>string dealer_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDealerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->dealer_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string zipcode = 3;</code>
     * @return string
     */
    public function getZipcode()
    {
        return $this->zipcode;
    }

    /**
     * Generated from protobuf field <code>string zipcode = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setZipcode($var)
    {
        GPBUtil::checkString($var, True);
        $this->zipcode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string is_inventory_sync = 4;</code>
     * @return string
     */
    public function getIsInventorySync()
    {
        return isset($this->is_inventory_sync) ? $this->is_inventory_sync : '';
    }

    public function hasIsInventorySync()
    {
        return isset($this->is_inventory_sync);
    }

    public function clearIsInventorySync()
    {
        unset($this->is_inventory_sync);
    }

    /**
     * Generated from protobuf field <code>optional string is_inventory_sync = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIsInventorySync($var)
    {
        GPBUtil::checkString($var, True);
        $this->is_inventory_sync = $var;

        return $this;
    }

}

