<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/Incentives/protos/genericIncentive.proto

namespace Incentive;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Incentive.SpecialIncentives</code>
 */
class SpecialIncentives extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ProgramName = 1;</code>
     */
    protected $ProgramName = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string group_affiliation = 3;</code>
     */
    protected $group_affiliation = '';
    /**
     * Generated from protobuf field <code>string previous_ownership = 4;</code>
     */
    protected $previous_ownership = '';
    /**
     * Generated from protobuf field <code>string program_id = 5;</code>
     */
    protected $program_id = '';
    /**
     * Generated from protobuf field <code>string StartDate = 6;</code>
     */
    protected $StartDate = '';
    /**
     * Generated from protobuf field <code>string EndDate = 7;</code>
     */
    protected $EndDate = '';
    /**
     * Generated from protobuf field <code>string description = 8;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>repeated .Incentive.Detail details = 9;</code>
     */
    private $details;
    /**
     * Generated from protobuf field <code>double cash_value = 10;</code>
     */
    protected $cash_value = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ProgramName
     *     @type string $name
     *     @type string $group_affiliation
     *     @type string $previous_ownership
     *     @type string $program_id
     *     @type string $StartDate
     *     @type string $EndDate
     *     @type string $description
     *     @type array<\Incentive\Detail>|\Google\Protobuf\Internal\RepeatedField $details
     *     @type float $cash_value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Src\Incentives\Protos\GenericIncentive::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ProgramName = 1;</code>
     * @return string
     */
    public function getProgramName()
    {
        return $this->ProgramName;
    }

    /**
     * Generated from protobuf field <code>string ProgramName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProgramName($var)
    {
        GPBUtil::checkString($var, True);
        $this->ProgramName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string group_affiliation = 3;</code>
     * @return string
     */
    public function getGroupAffiliation()
    {
        return $this->group_affiliation;
    }

    /**
     * Generated from protobuf field <code>string group_affiliation = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupAffiliation($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_affiliation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string previous_ownership = 4;</code>
     * @return string
     */
    public function getPreviousOwnership()
    {
        return $this->previous_ownership;
    }

    /**
     * Generated from protobuf field <code>string previous_ownership = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPreviousOwnership($var)
    {
        GPBUtil::checkString($var, True);
        $this->previous_ownership = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string program_id = 5;</code>
     * @return string
     */
    public function getProgramId()
    {
        return $this->program_id;
    }

    /**
     * Generated from protobuf field <code>string program_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setProgramId($var)
    {
        GPBUtil::checkString($var, True);
        $this->program_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string StartDate = 6;</code>
     * @return string
     */
    public function getStartDate()
    {
        return $this->StartDate;
    }

    /**
     * Generated from protobuf field <code>string StartDate = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setStartDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->StartDate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string EndDate = 7;</code>
     * @return string
     */
    public function getEndDate()
    {
        return $this->EndDate;
    }

    /**
     * Generated from protobuf field <code>string EndDate = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setEndDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->EndDate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 8;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Incentive.Detail details = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Generated from protobuf field <code>repeated .Incentive.Detail details = 9;</code>
     * @param array<\Incentive\Detail>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDetails($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Incentive\Detail::class);
        $this->details = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double cash_value = 10;</code>
     * @return float
     */
    public function getCashValue()
    {
        return $this->cash_value;
    }

    /**
     * Generated from protobuf field <code>double cash_value = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setCashValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->cash_value = $var;

        return $this;
    }

}

