<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/Incentives/protos/genericIncentive.proto

namespace Incentive;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Incentive.Terms</code>
 */
class Terms extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 length = 1;</code>
     */
    protected $length = 0;
    /**
     * Generated from protobuf field <code>double rate = 2;</code>
     */
    protected $rate = 0.0;
    /**
     * Generated from protobuf field <code>string per_1000 = 3;</code>
     */
    protected $per_1000 = '';
    /**
     * Generated from protobuf field <code>string disclosure = 4;</code>
     */
    protected $disclosure = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $length
     *     @type float $rate
     *     @type string $per_1000
     *     @type string $disclosure
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Src\Incentives\Protos\GenericIncentive::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 length = 1;</code>
     * @return int
     */
    public function getLength()
    {
        return $this->length;
    }

    /**
     * Generated from protobuf field <code>int32 length = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLength($var)
    {
        GPBUtil::checkInt32($var);
        $this->length = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double rate = 2;</code>
     * @return float
     */
    public function getRate()
    {
        return $this->rate;
    }

    /**
     * Generated from protobuf field <code>double rate = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setRate($var)
    {
        GPBUtil::checkDouble($var);
        $this->rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string per_1000 = 3;</code>
     * @return string
     */
    public function getPer1000()
    {
        return $this->per_1000;
    }

    /**
     * Generated from protobuf field <code>string per_1000 = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPer1000($var)
    {
        GPBUtil::checkString($var, True);
        $this->per_1000 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string disclosure = 4;</code>
     * @return string
     */
    public function getDisclosure()
    {
        return $this->disclosure;
    }

    /**
     * Generated from protobuf field <code>string disclosure = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDisclosure($var)
    {
        GPBUtil::checkString($var, True);
        $this->disclosure = $var;

        return $this;
    }

}

